# NumPy (Numerical Python)
---
- Python'da programlama dünyasından, veri analitiği dünyasına kapan açan kütüphanedir. Bilimsel hesaplamalar için kullanılır.
- **Neden NumPy?**; 
    - İçerisinde tek bir veri tipi barındırdığından dolayı daha hızlıdır. (fix type)
    - Verimli veri saklama ve vektörel operasyonları gerçekleştirir.
    - Daha az çaba ile daha fazla iş yapar.
    - Array'ler, çok boyutlu array'ler ve matrisler üzerinde yüksek performanslı çalışma imkanı sağlar.
- Bu yönleriyle Python listelerinden farklıdır. Bundan dolayı NumPy tercih edilir.
---
### Numpy Array Oluşturma
- **NumPy**'ın kendine has bir veri yapısı vardır; **_ndarray_**
- **NumPy array**'ler _Python_'da bulunan veri yapıları gibi bir veri yapısıdır.
- NumPy'da işlem gerçekleştirirken **ndarray**'a ihtiyaç duyarız.

In [1]:
import numpy as np
np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

- liste yapısını üzerinde array oluşturduk.

In [2]:
type(np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]))

numpy.ndarray

- Kendimiz istediğimiz düzeyde, sınırda ve sıralamada array oluşturabiliriz.

In [3]:
np.zeros(5, dtype = int)

array([0, 0, 0, 0, 0])

- 0'lardan oluşan tipi integer olan bir array oluşturduk.

In [4]:
np.random.randint(0, 20, size = 10)

array([13, 11, 15, 10, 11,  1, 19,  3, 11,  2])

- içerisinde 0' dan 20'e kadar rastgele 10 adet integer bulunduran bir array oluşturduk.

In [5]:
np.random.normal(10, 4, (3, 4))

array([[ 2.54749671, 11.00366467, 13.72260572, 15.92689659],
       [12.65816083, 13.8305289 , 11.41818336,  4.75763456],
       [10.14114885, 17.43829675, 17.15991687,  8.87276502]])

- ortalaması 10, standart sapması 4 olan üçe dörtlük bir array oluşturduk.

### NumPy Array Özellikleri
---
- **ndim**; boyut sayısı
- **shape**; boyut bilgisi
- **size**; toplam eleman sayısı
- **dtype**; array'in içinde barındırılan verinin tipi

In [6]:
a = np.random.randint(10, size = 5)

In [7]:
a.ndim

1

In [8]:
a.shape

(5,)

In [9]:
a.size

5

In [10]:
a.dtype

dtype('int64')

#### Reshaping
---
- Bir array'in boyutunu değiştirmek için kullanıyoruz.

In [11]:
np.random.randint(1, 10, size = 9)

array([4, 3, 6, 9, 7, 8, 3, 9, 9])

- 1'den 10'a kadar tek boyutlu rastgele integer barındıran bir array oluşturduk.

In [12]:
np.random.randint(1, 10, size = 9).reshape(3, 3)

array([[5, 1, 7],
       [6, 2, 2],
       [6, 1, 2]])

- oluşturduğumuz array'i üçe üçlük iki boyutlu bir array'e dönüştürdük.

In [13]:
ar = np.random.randint(1, 10, size = 9)
ar.reshape(3, 3)

array([[1, 2, 6],
       [2, 6, 7],
       [4, 8, 2]])

- Bir değişkene atayıp o değişken üzerinden de _reshaping_ yapabilirdik.
- Dikkat edilmesi gereken nokta; array'in eleman sayısı ile dönüştürülecek satır, sütun sayısı.

#### Index Selection
---
- Veri yapılarının üzerinde çalışırken, bu veri yapılarının içerisinde barındırdığı verilere ulaşmak isteyebiliriz.
- **Index Selection**; bu verilere ulaşmak için kullandığımız yöntemlerdir.

In [14]:
a = np.random.randint(10, size = 10)

In [15]:
a

array([5, 9, 0, 8, 0, 4, 2, 4, 7, 2])

In [16]:
a[0] # 0. index'e ulaşmak istersek.

5

In [17]:
a[0:5] # 0'dan (0 dahil) 5'e kadar (5 hariç) slicing işlemi.

array([5, 9, 0, 8, 0])

In [18]:
m = np.random.randint(10, size = (3, 5))

In [19]:
m # 3 satırlı, 5 sütunlu bir array'de index işlemleri

array([[9, 8, 0, 7, 4],
       [8, 4, 2, 9, 9],
       [6, 3, 7, 9, 8]])

In [20]:
m[0, 0]

9

In [21]:
m[2, 3]

9

### Fancy Index
---
- Bazı zamanlarda elimizde birçok index bilgisi olabilir. İlgili array'e indexleri liste şeklinde gönderdiğimizde o liste değerlerine karşılık gelen index bilgilerini bize döndürür.

In [22]:
v = np.arange(0, 30, 3)

In [23]:
v[1]

3

In [24]:
v[3]

9

In [25]:
catch = [1, 2, 3]
v[catch]

array([3, 6, 9])

### Conditions on NumPy
---
- Amacımız oluşturduğumuz np.array'de 3'den küçük değerlere erişmek.

In [26]:
v = np.array([1, 2, 3, 4, 5])

In [27]:
# klasik döngü ile

ab = []
for i in v:
    if i < 3:
        ab.append(i)

ab

[1, 2]

In [28]:
# NumPy ile

v < 3 # koşulu sağlayan, sağlamayan tüm değerleri boolean tipinde bize döndürdü.

array([ True,  True, False, False, False])

In [29]:
v[v < 3] # koşulu sağlayan değerleri görmek için;

array([1, 2])

### Mathematical Operations

In [30]:
v = np.array([1, 2, 3, 4, 5])
v

array([1, 2, 3, 4, 5])

In [31]:
v / 5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [32]:
v * 5 / 10

array([0.5, 1. , 1.5, 2. , 2.5])

- **NumPy metodları** ile matematiksel işlemler gerçekleştirelim;

In [34]:
v

array([1, 2, 3, 4, 5])

In [33]:
np.subtract(v, 1)

array([0, 1, 2, 3, 4])

- array içerisinde bulunan elemanlardan "1" çıkarttı.

In [35]:
np.add(v, 1)

array([2, 3, 4, 5, 6])

- array içerisinde bulunan elemanlara "1" ekledi.

In [36]:
np.mean(v)

3.0

- array'in ortalamasını aldı.

In [37]:
np.sum(v)

15

- array içerisinde bulunan tüm elemanları topladı.

In [38]:
np.min(v)

1

- array içerisinde bulunan minimum değerde olan eleman.

In [39]:
np.max(v)

5

- array içerisinde bulunan maksimum değerde olan eleman.

In [40]:
np.var(v)

2.0

- array varyans

### NumPy ile iki bilinmeyenli denklem çözümü;
- 5*x0 + x1 = 12
- x0 + 3*x1 = 10

In [41]:
a = np.array([[5, 1], [1, 3]])
b = np.array([12, 10])

np.linalg.solve(a, b)

array([1.85714286, 2.71428571])